export const HARDCODED_MEDICINE_DATA = {
    medicines: [
        {
            name: "Augmentin 625mg",
            imageUrl: null,
            uses: [
                "Treatment of bacterial infections such as urinary tract infections (UTIs)",
                "Sinus infections (sinusitis)",
                "Pneumonia",
                "Ear infections (otitis media)",
                "Skin and soft tissue infections (e.g., cellulitis)",
                "Lower respiratory tract infections",
                "Bone and joint infections (e.g., osteomyelitis)",
                "Dental infections (e.g., dentoalveolar abscess)",
            ],
            sideEffects: {
                common: ["Diarrhea", "Nausea", "Rash"],
                serious: [
                    "Cholestatic jaundice",
                    "Hepatic dysfunction",
                    "Severe allergic reactions (e.g., anaphylaxis, swelling of face/lips/tongue, hives, skin rashes, eosinophilia)",
                    "Interstitial nephritis",
                    "Crystalluria",
                ],
                rare: [],
            },
            warningsAndPrecautions: [
                "Use with caution in patients with hepatic dysfunction; monitor liver function regularly.",
                "Contraindicated in patients with a history of hypersensitivity to beta-lactams (e.g., penicillins, cephalosporins) or to any of the excipients.",
                "Contraindicated in patients with a history of jaundice/hepatic impairment due to amoxicillin/clavulanic acid.",
                "Augmentin chewable tablets and oral suspension (200mg/5mL or 400mg/5mL) contain aspartame and should not be used by phenylketonurics.",
                "Should only be used to treat infections proven or strongly suspected to be caused by susceptible bacteria to reduce drug resistance.",
                "Dosage adjustment is required in patients with severe renal impairment (CrCl < 30 mL/min).",
                "Not recommended for children 12 years and under in the 625mg tablet form; suspension or pediatric sachets are preferred for younger children.",
            ],
            interactions: {
                drugInteractions: [
                    "Warfarin (increased risk of bleeding; monitor prothrombin time/INR)",
                    "Methotrexate (increased methotrexate levels and toxicity)",
                    "Allopurinol (increased risk of rash)",
                    "Probenecid (increased and prolonged blood levels of amoxicillin)",
                    "Combined oral contraceptives (may decrease effectiveness; consider additional birth control)",
                    "Other NSAIDs, metformin, opioids, GLP-1 medications (may increase stomach-related side effects)",
                    "Mycophenolate mofetil (reduction in pre-dose concentration of mycophenolic acid)",
                ],
                foodInteractions: [
                    "Should be taken at the start of a meal to minimize potential gastrointestinal intolerance.",
                ],
                conditionInteractions: [
                    "Liver disease (hepatic dysfunction)",
                    "Kidney disease (renal impairment)",
                    "Mononucleosis (increased risk of rash)",
                    "History of gastrointestinal toxicity (especially elderly patients)",
                    "Ulcerative colitis or Crohn's disease (may be exacerbated)",
                    "Asthma, seasonal allergic rhinitis, nasal polyps, chronic obstructive pulmonary disease, chronic respiratory tract infections (increased risk of asthma exacerbations, angioedema, urticaria).",
                ],
            },
            overdoseMissedDose: {
                overdose:
                    "In case of overdose, discontinue medication, treat symptomatically, and institute supportive measures. Interstitial nephritis leading to oliguric renal failure and crystalluria have been reported. Maintain adequate fluid intake and diuresis. Hemodialysis can remove amoxicillin and clavulanate potassium from circulation.",
                missedDose:
                    "Take the missed dose as soon as you remember. If it is almost time for your next dose, skip the missed dose and resume your regular dosing schedule. Do not double the dose to make up for a missed one.",
            },
            approximatePrice: {
                currency: "USD",
                priceRange: "$6.87 - $39.10",
                unit: "per 20 tablets (generic 875mg/125mg, used as estimate for 625mg due to common availability)",
                lastUpdated: "2025",
            },
            manufacturer: [
                "GlaxoSmithKline (GSK)",
                "Aurobindo Pharma Ltd.",
                "Cipla",
                "Hikma Pharmaceuticals",
                "Micro Labs",
                "Sandoz Inc.",
                "Teva",
            ],
            activeIngredients: [
                {
                    name: "Amoxicillin",
                    strength: "500 mg",
                    purpose:
                        "Antibiotic (kills bacteria by preventing cell wall formation)",
                },
                {
                    name: "Clavulanate Potassium (as clavulanic acid)",
                    strength: "125 mg",
                    purpose:
                        "Beta-lactamase inhibitor (protects amoxicillin from bacterial enzymes)",
                },
            ],
            dosageForm: "Oral tablet (film-coated)",
            prescriptionRequired: true,
            genericAvailable: true,
            fdaApproved: true,
            lastUpdated: "August 2025",
        },
        {
            name: "Enzoflam",
            imageUrl: null,
            uses: [
                "Pain and inflammation relief (e.g., osteoarthritis, rheumatoid arthritis, ankylosing spondylitis)",
                "Muscle pain",
                "Tooth pain (including post-dental surgery)",
                "Bone and joint pain",
                "Headache",
                "Swelling",
                "Period pain (menstrual cramps)",
                "Ear pain",
                "Migraine",
                "Fever",
                "Sore throat",
                "Nose pain",
                "Post-surgical pain management",
            ],
            sideEffects: {
                common: [
                    "Nausea",
                    "Vomiting",
                    "Dizziness",
                    "Indigestion",
                    "Stomach pain",
                    "Constipation",
                    "Diarrhea",
                    "Bloating",
                    "Heartburn",
                    "Loss of appetite",
                    "Headache",
                    "Vertigo",
                    "Increased liver enzymes",
                ],
                serious: [
                    "Severe allergic reactions (rash, itching, swelling, severe dizziness, trouble breathing, hives, angioedema, anaphylactic shock)",
                    "Liver issues (yellowing of skin or eyes, dark urine, severe stomach pain, liver damage)",
                    "Severe stomach issues (persistent stomach pain, black tarry stools, vomit that looks like coffee grounds, ulcers, gastrointestinal bleeding)",
                    "Anorexia",
                    "Urine in blood",
                    "Weakness",
                    "Unusual bleeding",
                ],
                rare: [],
            },
            warningsAndPrecautions: [
                "Unsafe during pregnancy, especially in the last trimester; should not be taken by pregnant women.",
                "Advised not to use while breastfeeding.",
                "Avoid alcohol consumption (may increase risk of liver damage, excessive drowsiness, stomach bleeding).",
                "Use with caution in patients with liver disease or kidney disease; not recommended for severe liver diseases.",
                "Use with caution in patients with heart problems (high blood pressure, heart failure).",
                "Caution in patients with gastrointestinal problems (history of stomach ulcers, bleeding, perforation, Crohn's disease).",
                "Patients with asthma, rhinitis, swelling of face/lips/tongue, or hives after taking aspirin or other NSAIDs should inform their doctor.",
                "Do not take more than the daily prescribed dose as it may affect the liver or cause allergic reactions.",
                "Do not take any other paracetamol-containing products concurrently.",
                "May cause dizziness and sleepiness; avoid driving or operating machinery until effects are known.",
                "Not recommended for children under 18 without medical supervision.",
                "Older patients should take under medical supervision due to increased susceptibility to side effects and potential liver/kidney issues.",
            ],
            interactions: {
                drugInteractions: [
                    "Medicines containing Acetaminophen (increased risk of liver damage)",
                    "Other Non-Steroidal Anti-Inflammatory Drugs (NSAIDs) like ibuprofen, aspirin, naproxen (increased side effects like stomach upset, ulcers, GI bleeding)",
                    "Anticoagulants like warfarin (increased risk of bleeding)",
                    "Lithium (may increase plasma concentrations of lithium)",
                    "Digoxin (may raise plasma concentrations of digoxin)",
                    "Diuretics and antihypertensive agents (e.g., beta-blockers, ACE inhibitors - may reduce efficacy)",
                    "Methotrexate (increased blood concentrations and toxicity)",
                    "Immunosuppressants like ciclosporin (increased nephrotoxicity)",
                    "Anti-diabetic medicines (can cause symptoms of low glucose levels)",
                    "Systemic corticosteroids, selective serotonin-reuptake inhibitors (SSRIs), anti-platelet agents (increased risk of ulceration or bleeding).",
                ],
                foodInteractions: [
                    "Generally recommended to take with food to minimize gastrointestinal side effects such as nausea and indigestion.",
                ],
                conditionInteractions: [
                    "Allergy to paracetamol, diclofenac, serratiopeptidase, or any other ingredients.",
                    "History of allergies including asthma, skin rashes, or runny nose after taking ibuprofen or aspirin.",
                    "History of frequent stomach ulcers or bleeding.",
                    "Heart disease (heart failure, high blood pressure).",
                    "Kidney or liver function problems.",
                    "Pregnancy (especially last trimester).",
                    "Alcohol abuse (increased risk of liver damage).",
                ],
            },
            overdoseMissedDose: {
                overdose:
                    "Enzoflam Tablet contains components that can cause severe liver and kidney damage when taken in high doses. Overdosing can also result in headaches, nausea, vomiting, and stomach pain. If overdose is suspected, contact your doctor or go to the nearest hospital immediately.",
                missedDose:
                    "If you miss a dose, take it as soon as you remember. If it is almost time for your next dose, skip the missed dose and take your next dose at the regularly scheduled time. Do not double doses.",
            },
            approximatePrice: {
                currency: "INR",
                priceRange: "₹136 - ₹170",
                unit: "per 10 tablets",
                lastUpdated: "2025",
            },
            manufacturer: ["Alkem Laboratories Ltd."],
            activeIngredients: [
                {
                    name: "Diclofenac",
                    strength: "50 mg",
                    purpose:
                        "Nonsteroidal anti-inflammatory drug (NSAID) - reduces pain and swelling.",
                },
                {
                    name: "Paracetamol (Acetaminophen)",
                    strength: "325 mg",
                    purpose:
                        "Analgesic and antipyretic - blocks chemical messengers causing pain and fever.",
                },
                {
                    name: "Serratiopeptidase",
                    strength: "15 mg",
                    purpose:
                        "Enzyme - reduces inflammation and promotes healing by breaking down abnormal proteins.",
                },
            ],
            dosageForm: "Tablet",
            prescriptionRequired: true,
            genericAvailable: true,
            fdaApproved: false,
            lastUpdated: "August 2025",
        },
        {
            name: "Pan-D 40mg",
            imageUrl: null,
            uses: [
                "Gastroesophageal reflux disease (GERD)",
                "Acidity",
                "Heartburn",
                "Nausea",
                "Vomiting",
                "Peptic ulcers (gastric and duodenal ulcers)",
                "Dyspepsia (indigestion)",
                "Zollinger-Ellison syndrome",
                "Erosive esophagitis",
                "Upper abdominal discomfort",
                "Bloating and gas",
            ],
            sideEffects: {
                common: [
                    "Headache",
                    "Dizziness",
                    "Stomach pain (abdominal pain)",
                    "Diarrhea",
                    "Constipation",
                    "Flatulence (gas)",
                    "Dry mouth",
                    "Nausea/Vomiting",
                    "Facial edema (swelling in the face)",
                    "Generalized edema",
                    "Pruritus (itching)",
                    "Rash",
                    "Hyperglycemia (high blood glucose)",
                    "Vitamin B12 Deficiency",
                    "Fundic gland polyps",
                    "Increased prolactin levels",
                    "Amenorrhea (absence of menstruation)",
                    "Gynecomastia (breast enlargement in males)",
                    "Breast pain and tenderness",
                    "Urticaria (hives)",
                    "Nervousness",
                    "Anxiety",
                    "Altered sense of taste",
                    "Joint/muscle pain",
                ],
                serious: [
                    "Irregular heartbeat or chest pain",
                    "Severe allergic reaction (rash, swelling, difficulty breathing)",
                    "Unusual tiredness or muscle weakness (may indicate low magnesium)",
                    "Persistent diarrhea with abdominal pain or fever (possible Clostridium difficile-associated diarrhea)",
                    "Signs of liver issues (yellowing of skin or eyes, dark urine)",
                    "Black, tarry stools or vomit that looks like coffee grounds (indicating GI bleeding)",
                ],
                rare: [],
            },
            warningsAndPrecautions: [
                "Contraindicated if allergic to pantoprazole, domperidone, or other components.",
                "Not generally considered safe during pregnancy as it could cause congenital defects.",
                "Should be used with caution during breastfeeding; breastfeeding should be held until treatment is completed and the drug is eliminated from the mother's body.",
                "Avoid alcohol consumption (can worsen side effects, increase drowsiness, dizziness, and acidity).",
                "Use with caution in patients with liver disease or kidney disease; dosage adjustment may be needed for kidney disease.",
                "Caution if there is a history of heart issues, including heart failure, heart rhythm disorders (QT prolongation), or electrolyte imbalance.",
                "Not recommended for children younger than five years.",
                "Long-term use (more than one year) can lead to weak bones (osteoporosis), low magnesium levels, and Vitamin B12 deficiency; calcium and magnesium supplements may be needed.",
                "May cause dizziness and sleepiness; avoid driving or operating heavy machinery until effects are known.",
                "Inform your doctor if you experience watery diarrhea, fever, or persistent stomach pain.",
                "If symptoms do not improve after 14 days, consult your doctor as there may be another underlying problem.",
            ],
            interactions: {
                drugInteractions: [
                    "Blood thinners (Clopidogrel, Warfarin - increased risk of bleeding)",
                    "Antifungals (Ketoconazole, Voriconazole, Itraconazole, Posaconazole - may reduce absorption due to stomach pH change)",
                    "Anti-HIV drugs (Atazanavir, Nelfinavir - may reduce absorption)",
                    "Iron supplements (may reduce absorption)",
                    "Antibiotics (Ampicillin, Rifampicin)",
                    "Heart medicine (Digoxin)",
                    "Anti-cancer drug (Methotrexate)",
                ],
                foodInteractions: [
                    "Recommended to be taken on an empty stomach, preferably 30-60 minutes before breakfast.",
                    "Avoid spicy and fatty foods, caffeinated drinks (tea, coffee), soft drinks like cola, and alcoholic beverages as they can worsen acidity.",
                ],
                conditionInteractions: [
                    "Hypersensitivity to pantoprazole or domperidone.",
                    "QT prolongation",
                    "Electrolyte disturbance",
                    "Cardiac disease (heart failure, heart rhythm problems)",
                    "GI hemorrhage (bleeding in the stomach or intestine)",
                    "Hepatic impairment (liver disease), moderate to severe",
                    "Kidney disease",
                    "Stomach tumour or cancer",
                    "Prolactin pituitary tumours",
                    "Osteoporosis (brittle or weak bones)",
                ],
            },
            overdoseMissedDose: {
                overdose:
                    "An overdose of Pan-D may cause symptoms such as dizziness, restlessness, dry mouth, or stomach discomfort. Severe overdose could lead to irregular heartbeat or confusion. Seek immediate medical help if an overdose is suspected.",
                missedDose:
                    "Take the missed dose as soon as you remember. If it is almost time for your next dose, skip the missed dose and resume your regular dosing schedule. Do not double the dose to make up for a missed one.",
            },
            approximatePrice: {
                currency: "INR",
                priceRange: "₹100 - ₹250",
                unit: "per strip of 10-15 capsules",
                lastUpdated: "2025",
            },
            manufacturer: ["Alkem Laboratories Ltd."],
            activeIngredients: [
                {
                    name: "Pantoprazole",
                    strength: "40 mg",
                    purpose:
                        "Proton Pump Inhibitor (PPI) - reduces stomach acid production.",
                },
                {
                    name: "Domperidone",
                    strength: "30 mg",
                    purpose:
                        "Prokinetic and antiemetic - increases movement of the upper gastrointestinal tract and reduces nausea/vomiting.",
                },
            ],
            dosageForm: "Capsule (often sustained-release, SR)",
            prescriptionRequired: true,
            genericAvailable: true,
            fdaApproved: false,
            lastUpdated: "August 2025",
        },
        {
            name: "Hexigel gum paint",
            imageUrl: null,
            uses: [
                "Treatment of inflammation of gums (gingivitis)",
                "Mouth infection",
                "Killing harmful microorganisms in the oral cavity",
                "Reducing dental plaque and tartar buildup",
                "Alleviating bad odor from the mouth",
                "Management of aphthous ulcers and other oral ulcers",
                "Application on wound surfaces after oral surgical procedures",
                "Treatment of denture stomatitis and thrush",
            ],
            sideEffects: {
                common: [
                    "Taste change",
                    "Staining of teeth and tongue",
                    "Hard dental plaque",
                    "Dryness in mouth",
                    "Loss of taste sensation",
                ],
                serious: [
                    "Allergic reaction",
                    "Immune disorders",
                    "Hypersensitivity",
                    "Anaphylactic shock",
                ],
                rare: [],
            },
            warningsAndPrecautions: [
                "Should be used exactly as prescribed by your doctor; follow dose and duration instructions.",
                "Avoid eating, drinking, or smoking for at least 30 minutes after using to allow the gel to work effectively.",
                "May cause permanent discoloration of tooth fillings.",
                "Avoid contact with eyes and ears.",
                "Brushing teeth with regular toothpaste before using can help prevent staining.",
                "Avoid tannin-containing food and drinks such as tea, coffee, and red wine to minimize staining.",
                "Information regarding safety during pregnancy and breastfeeding is limited/not available; consult your doctor if pregnant or breastfeeding.",
                "Generally considered safe with little or no systemic side effects.",
            ],
            interactions: {
                drugInteractions: [
                    "Not likely to interact with other medicines taken by mouth or injection due to topical application and low systemic absorption. However, consult your doctor if you have had an allergic reaction to similar medicines before.",
                ],
                foodInteractions: [
                    "Avoid eating or drinking for at least 30 minutes after application.",
                    "Avoid tea, coffee, and red wine due to potential for teeth staining.",
                ],
                conditionInteractions: [
                    "History of allergic reaction to similar medicines (e.g., chlorhexidine).",
                ],
            },
            overdoseMissedDose: {
                overdose:
                    "Overdose is unlikely with topical gum paint due to low systemic absorption. If swallowed in large quantities, symptoms are generally mild. Seek medical advice if excessive ingestion occurs. (Information is limited; general advice applies).",
                missedDose:
                    "Apply the missed dose as soon as you remember. If it is almost time for your next scheduled application, skip the missed dose and resume your regular schedule. Do not apply extra to make up for a missed dose.",
            },
            approximatePrice: {
                currency: "INR",
                priceRange: "₹75 - ₹80",
                unit: "per 15g tube",
                lastUpdated: "2025",
            },
            manufacturer: ["ICPA Health Products Ltd."],
            activeIngredients: [
                {
                    name: "Chlorhexidine Gluconate",
                    strength:
                        "1.0% (standard concentration in similar products, implied from uses and product type)",
                    purpose:
                        "Antiseptic (kills harmful microorganisms, binds to teeth/gums)",
                },
            ],
            dosageForm: "Mouth Gel / Gum Paint",
            prescriptionRequired: true,
            genericAvailable: true,
            fdaApproved: false,
            lastUpdated: "August 2025",
        },
    ],
    searchMetadata: {
        searchDate: "August 11, 2025",
        sourcesCount: "32",
        reliability: "high",
    },
};
