# -*- coding: utf-8 -*-
"""Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PijSEPVCih8p_ICBSexFlhUaNTdQOMs8
"""


import pytesseract

import numpy as np
from matplotlib import pyplot as plt
import cv2 #opencv
from google.colab.patches import cv2_imshow


def read_prescription(image_path: str) -> str:
   # 1. Load image
    img = cv2.imread(image_path)
    if img is None:
        return "Error: Image not found."

    # 2. Preprocess
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # noise reduction + thresholding
    blur = cv2.GaussianBlur(gray, (3,3), 0)
    thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]

    # 3. OCR with pytesseract
    config = "--oem 3 --psm 6"  # LSTM OCR Engine + Assume block of text
    text = pytesseract.image_to_string(thresh, config=config)

    return text.strip()

